name: Deploy

on:
  workflow_run:
    workflows: ["Python CI", "TypeScript CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python and Node.js
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Download Python Lambda artifact
        uses: actions/download-artifact@v3
        with:
          name: python-lambda
          path: my_python_service/build

      - name: Download TypeScript Lambda artifact
        uses: actions/download-artifact@v3
        with:
          name: typescript-lambda
          path: my_ts_service/build

      - name: List files for debugging (Python)
        run: ls -R my_python_service/build

      - name: List files for debugging (TypeScript)
        run: ls -R my_ts_service/build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform
