name: Deploy

on:
  workflow_run:
    workflows: ["Python CI", "TypeScript CI"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get Python CI run ID
        id: python_run_id
        run: |
          python_run_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/python-ci.yml/runs | jq -r '.workflow_runs[] | select(.head_sha == "${{ github.event.workflow_run.head_sha }}") | .id')
          echo "::set-output name=run_id::$python_run_id"

      - name: Download Python Lambda artifact
        uses: actions/download-artifact@v3
        with:
          name: python-lambda
          path: my_python_service/build

      - name: Get TypeScript CI run ID
        id: typescript_run_id
        run: |
          typescript_run_id=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/workflows/typescript-ci.yml/runs | jq -r '.workflow_runs[] | select(.head_sha == "${{ github.event.workflow_run.head_sha }}") | .id')
          echo "::set-output name=run_id::$typescript_run_id"

      - name: Download TypeScript Lambda artifact
        uses: actions/download-artifact@v3
        with:
          name: typescript-lambda
          path: my_ts_service/build

      - name: List files for debugging (Python)
        run: ls -R my_python_service/build

      - name: List files for debugging (TypeScript)
        run: ls -R my_ts_service/build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Initialize Terraform
        run: terraform init
        working-directory: terraform

      - name: Apply Terraform
        run: terraform apply -auto-approve
        working-directory: terraform