name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r my_python_service/requirements.txt

      - name: Run tests
        working-directory: my_python_service
        run: pytest

      - name: Set up GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: List and delete all artifacts
        run: |
          gh api -X GET repos/${{ github.repository }}/actions/artifacts --paginate --jq '.artifacts[].id' | while read -r artifact_id; do
            gh api -X DELETE repos/${{ github.repository }}/actions/artifacts/$artifact_id
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create build directory
        run: mkdir -p my_python_service/build

      - name: Zip function
        run: zip -r my_python_service/build/function.zip my_python_service/src

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: python-lambda
          path: my_python_service/build/function.zip

      - name: Output Run ID
        run: echo ${{ github.run_id }} > run_id.txt

      - name: Upload Run ID
        uses: actions/upload-artifact@v3
        with:
          name: python-run-id
          path: run_id.txt