name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r my_python_service/requirements.txt

      - name: Run tests
        run: |
          pytest my_python_service/src/test_main.py

      - name: Package lambda
        run: |
          cd my_python_service/src
          zip -r function.zip .
          cd ../..

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-lambda
          path: my_python_service/src/function.zip

      - name: Output Run ID
        run: echo ${{ github.run_id }} > run_id.txt

      - name: Upload Run ID
        uses: actions/upload-artifact@v4
        with:
          name: python-run-id
          path: run_id.txt