name: TypeScript CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      actions: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd my_ts_service
          npm install

      - name: Build project
        run: |
          cd my_ts_service
          npm run build

      - name: Set up GitHub CLI
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: List and delete all artifacts
        run: |
          gh api -X GET repos/${{ github.repository }}/actions/artifacts --paginate --jq '.artifacts[].id' | while read -r artifact_id; do
            gh api -X DELETE repos/${{ github.repository }}/actions/artifacts/$artifact_id
          done
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create build directory
        run: mkdir -p my_ts_service/build

      - name: Zip function
        run: zip -r my_ts_service/build/function.zip my_ts_service/dist

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-lambda-${{ github.sha }}
          path: my_ts_service/build/function.zip
