name: TypeScript CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: my_ts_service

      - name: Build the TypeScript service
        run: npm run build
        working-directory: my_ts_service

      - name: Create build directory
        run: mkdir -p my_ts_service/build
        working-directory: my_ts_service

      - name: Zip the built files
        run: zip -r my_ts_service/build/function.zip dist
        working-directory: my_ts_service

      - name: Upload TypeScript Lambda artifact
        uses: actions/upload-artifact@v3
        with:
          name: typescript-lambda
          path: my_ts_service/build/function.zip
