name: TypeScript CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: my_ts_service

    #   - name: Run tests
    #     run: npm test
    #     working-directory: my_ts_service

      - name: Build TypeScript project
        run: npm run build
        working-directory: my_ts_service

      - name: Package lambda
        run: |
          cd my_ts_service/dist
          zip -r function.zip .
          cd ../..

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: typescript-lambda
          path: my_ts_service/dist/function.zip
