name: TypeScript CI

on:
  push:
    paths:
      - 'my_ts_service/**'
  pull_request:
    paths:
      - 'my_ts_service/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: my_ts_service

      - name: Run build
        run: npm run build
        working-directory: my_ts_service

      - name: Package lambda
        run: zip -r function.zip dist/
        working-directory: my_ts_service

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: typescript-lambda
          path: my_ts_service/dist/
